DGtal: DGtal::CellGeometryFunctions< TKSpace, i, N > Struct Template Reference
DGtal::CellGeometryFunctions< TKSpace, i, N > Struct Template Reference
#include <DGtal/geometry/volumes/CellGeometry.h>
Public Types
typedef TKSpace KSpace
typedef KSpace::Space Space
typedef KSpace::Cell Cell
typedef KSpace::Point Point
Public Member Functions
BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< TKSpace >))
Static Public Member Functions
template<typename PointelIterator >
static std::unordered_set< typename KSpace::Cell > getIncidentCellsToPointels (const KSpace &K, PointelIterator itB, PointelIterator itE)
template<typename PointIterator >
static std::unordered_set< typename KSpace::Cell > getIncidentCellsToPoints (const KSpace &K, PointIterator itB, PointIterator itE)
Detailed Description
template<typename TKSpace, int i, int N>
struct DGtal::CellGeometryFunctions< TKSpace, i, N >
Utility class gathering some useful functions related to cell geometry and digital or cell convexity. It is meant to be specialized for low dimensions.
Template Parameters
TKSpace an arbitrary model of CCellularGridSpaceND.
i the integer specifying the dimension of cells.
N the integer specifying the dimension of the digital space.
Definition at line 397 of file CellGeometry.h.
Member Typedef Documentation
Cell
template<typename TKSpace , int i, int N> typedef KSpace::Cell DGtal::CellGeometryFunctions< TKSpace, i, N >::Cell
Definition at line 402 of file CellGeometry.h.
KSpace
template<typename TKSpace , int i, int N> typedef TKSpace DGtal::CellGeometryFunctions< TKSpace, i, N >::KSpace
Definition at line 400 of file CellGeometry.h.
Point
template<typename TKSpace , int i, int N> typedef KSpace::Point DGtal::CellGeometryFunctions< TKSpace, i, N >::Point
Definition at line 403 of file CellGeometry.h.
Space
template<typename TKSpace , int i, int N> typedef KSpace::Space DGtal::CellGeometryFunctions< TKSpace, i, N >::Space
Definition at line 401 of file CellGeometry.h.
Member Function Documentation
BOOST_CONCEPT_ASSERT()
template<typename TKSpace , int i, int N> DGtal::CellGeometryFunctions< TKSpace, i, N >::BOOST_CONCEPT_ASSERT ((concepts::CCellularGridSpaceND< TKSpace >))
getIncidentCellsToPointels()
template<typename TKSpace , int i, int N> template<typename PointelIterator > static std::unordered_set<typename KSpace::Cell> DGtal::CellGeometryFunctions< TKSpace, i, N >::getIncidentCellsToPointels (const KSpace & K, PointelIterator itB, PointelIterator itE) inline static
Template Parameters
PointelIterator any model of forward iterator on pointels.
Parameters
K a valid cellular grid space large enough to hold the cells.
itB the start of a range of pointels.
itE past the end of a range of pointels.
Returns
the incident i-cells to the given range of pointels [itB, itE).
Note
General method. Note as efficient as specializations.
Definition at line 414 of file CellGeometry.h.
References K, DGtal::KhalimskySpaceND< dim, TInteger >::uCoFaces(), and DGtal::KhalimskySpaceND< dim, TInteger >::uDim().
     {
       std::unordered_set<typename KSpace::Cell> cells;
       if ( i == 0 )
         for ( auto it = itB; it != itE; ++it )
           cells.insert( *it );
       else
         for ( auto it = itB; it != itE; ++it )
           {
             auto pointel = *it;
             auto cofaces = K.uCoFaces( pointel );
             for ( auto&& f : cofaces )
               if ( K.uDim( f ) == i ) cells.insert( f );
           }
       return cells;
     }
getIncidentCellsToPoints()
template<typename TKSpace , int i, int N> template<typename PointIterator > static std::unordered_set<typename KSpace::Cell> DGtal::CellGeometryFunctions< TKSpace, i, N >::getIncidentCellsToPoints (const KSpace & K, PointIterator itB, PointIterator itE) inline static
Template Parameters
PointIterator any model of forward iterator on points.
Parameters
K a valid cellular grid space large enough to hold the cells.
itB the start of a range of points.
itE past the end of a range of points.
Returns
the incident i-cells to the given range of points [itB, itE).
Note
General method. Note as efficient as specializations.
Definition at line 441 of file CellGeometry.h.
References K, DGtal::KhalimskySpaceND< dim, TInteger >::uCoFaces(), DGtal::KhalimskySpaceND< dim, TInteger >::uDim(), and DGtal::KhalimskySpaceND< dim, TInteger >::uPointel().
     {
       std::unordered_set<typename KSpace::Cell> cells;
       if ( i == 0 )
         for ( auto it = itB; it != itE; ++it )
           cells.insert( K.uPointel( *it ) );
       else
         for ( auto it = itB; it != itE; ++it )
           {
             auto pointel = K.uPointel( *it );
             auto cofaces = K.uCoFaces( pointel );
             for ( auto&& f : cofaces )
               if ( K.uDim( f ) == i ) cells.insert( f );
           }
       return cells;
     }
The documentation for this struct was generated from the following file:
CellGeometry.h